### ISSUE TITLE
REST API no longer supports plain http; need to update BASE_URL to https

### ISSUE THREAD

**Issue by dsheroh** [LibreCat/Catmandu-EuropePMC#5]
BASE_URL uses plain http.  According to support personnel at EuropePMC, the REST API is now https-only, which causes requests from this module to time out.  Changing BASE_URL from http to https allows the REST interactions to complete successfully.

**Comment by vpeil** [comment]
@dsheroh I released that change 2 weeks ago, as of Version 0.18 it should be fixed.

https://github.com/LibreCat/Catmandu-EuropePMC/blob/master/Changes#L6

**Comment by dsheroh** [comment]
Strange.  I just did a fresh CPAN install earlier today and it didn't have that change.  Must have hit a stale mirror or something.  Thanks, in any case!
